const $=s=>document.querySelector(s), token=()=>localStorage.jasineToken; let current=null,signup=false,controller=null;
async function api(path,opt={}){let r=await fetch('/api'+path,{...opt,headers:{'Content-Type':'application/json',Authorization:'Bearer '+token(),...opt.headers}});if(!r.ok)throw new Error((await r.json()).error||'Request failed');return r}
function escape(s){return s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
function markdown(s){return escape(s).replace(/```([^\n]*)\n([\s\S]*?)```/g,'<pre><code>$2</code></pre>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/\n/g,'<br>')}
function showError(e){$('#error').textContent=e.message;$('#error').hidden=false;setTimeout(()=>$('#error').hidden=true,4000)}
async function boot(){if(!token())return;try{await api('/me');$('#auth').hidden=true;$('#app').hidden=false;await list()}catch(e){delete localStorage.jasineToken}}
$('#mode').onclick=()=>{signup=!signup;$('#mode').textContent=signup?'Already have an account? Sign in':'New here? Create an account'};
$('#authForm').onsubmit=async e=>{e.preventDefault();try{let r=await api(signup?'/register':'/login',{method:'POST',body:JSON.stringify({email:$('#email').value,password:$('#password').value})});localStorage.jasineToken=(await r.json()).token;boot()}catch(e){$('#authError').textContent=e.message}};
async function list(){let cs=await (await api('/conversations')).json();$('#conversations').innerHTML=cs.map(c=>`<div class="convrow ${c.id===current?'active':''}"><button class="conv" data-id="${c.id}">${escape(c.title)}</button><button class="remove" data-id="${c.id}" title="Delete conversation">×</button></div>`).join('');document.querySelectorAll('.conv').forEach(x=>x.onclick=()=>open(x.dataset.id));document.querySelectorAll('.remove').forEach(x=>x.onclick=()=>removeConversation(x.dataset.id));if(!current&&cs[0])open(cs[0].id)}
async function create(){let c=await (await api('/conversations',{method:'POST',body:'{}'})).json();current=c.id;await list();await open(c.id);$('#input').focus()}
async function open(id){current=id;let c=await (await api('/conversations/'+id)).json();$('#title').textContent=c.title;render(c.messages);list();$('#sidebar').classList.remove('open')}
function render(ms){$('#messages').innerHTML=ms.length?'':`<div class="welcome"><div class="orb">J</div><h1>What are we thinking about?</h1><p>Tell me what matters. I’ll remember useful context across conversations.</p></div>`;ms.forEach(add)}
function add(m){let d=document.createElement('div');d.className='message '+m.role;let actions=m.role==='assistant'?`<button onclick="feedback('${m.id}','up')">♡ Helpful</button><button onclick="feedback('${m.id}','down')">⌁ Not helpful</button><button onclick="correct('${m.id}')">✎ Correct</button><button onclick="feedback('${m.id}','regenerate')">↻ Regenerate</button>`:`<button class="edit">✎ Edit & resend</button>`;d.innerHTML=`<div class="avatar">${m.role==='assistant'?'J':'You'}</div><div class="bubble"><div>${markdown(m.content)}</div><div class="meta">${new Date(m.created_at||Date.now()).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</div><div class="actions">${actions}</div></div>`;let edit=d.querySelector('.edit');if(edit)edit.onclick=()=>{$('#input').value=m.content;$('#input').focus();$('#input').setSelectionRange(m.content.length,m.content.length)};$('#messages').append(d);$('#messages').scrollTop=1e9;return d}
$('#composer').onsubmit=async e=>{e.preventDefault();let text=$('#input').value.trim();if(!text)return;if(!current)await create();$('#input').value='';add({role:'user',content:text});let node=add({role:'assistant',content:'',created_at:new Date().toISOString()}), out=node.querySelector('.bubble>div');controller=new AbortController();$('#send').textContent='■';try{let r=await api('/conversations/'+current+'/chat',{method:'POST',body:JSON.stringify({message:text}),signal:controller.signal});let reader=r.body.getReader(),buf='',decoder=new TextDecoder();while(true){let {done,value}=await reader.read();if(done)break;buf+=decoder.decode(value,{stream:true});let lines=buf.split('\n');buf=lines.pop();for(let line of lines){let x=JSON.parse(line);if(x.type==='delta'){out.innerHTML+=markdown(x.text);$('#messages').scrollTop=1e9}}}await list()}catch(e){if(e.name!=='AbortError')showError(e)}finally{$('#send').textContent='↑';controller=null}};
$('#send').onclick=e=>{if(controller){e.preventDefault();controller.abort()}};$('#new').onclick=create;$('#logout').onclick=async()=>{try{await api('/logout',{method:'POST',body:'{}'})}finally{localStorage.removeItem('jasineToken');location.reload()}};$('#menu').onclick=()=>$('#sidebar').classList.add('open');$('#closeSide').onclick=()=>$('#sidebar').classList.remove('open');
$('#rename').onclick=async()=>{if(!current)return;let title=prompt('Conversation title',$('#title').textContent);if(title){await api('/conversations/'+current,{method:'PATCH',body:JSON.stringify({title})});open(current)}};
async function feedback(id,kind){try{await api('/feedback',{method:'POST',body:JSON.stringify({messageId:id,kind})});if(kind==='regenerate'){$('#input').value='Please answer my previous question again with a different approach.';$('#composer').requestSubmit()}}catch(e){showError(e)}}
async function correct(id){let comment=prompt('What should Jasine remember instead?');if(comment)try{let result=await(await api('/feedback',{method:'POST',body:JSON.stringify({messageId:id,kind:'correction',comment})})).json();alert(result.memoryWrites?'Correction learned.':'Feedback saved. Phrase the correction as a fact (for example, “My editor is Zed”) if you want it remembered.')}catch(e){showError(e)}}
async function removeConversation(id){if(!confirm('Delete this conversation? Long-term memories are retained until you ask Jasine to forget them.'))return;try{await api('/conversations/'+id,{method:'DELETE'});if(current===id){current=null;$('#title').textContent='New conversation';render([])}await list()}catch(e){showError(e)}}
function recordCard(x){let primary=x.content||x.name||x.model||x.kind||'Record';let details=Object.entries(x).filter(([k])=>!['embedding','content','name'].includes(k)).slice(0,8).map(([k,v])=>`${k}: ${typeof v==='string'?v:JSON.stringify(v)}`).join('\n');return `<div class="card"><span class="badge">${escape(x.type||x.kind||'record')}</span><strong>${escape(String(primary))}</strong><pre>${escape(details)}</pre></div>`}
$('#brain').onclick=async()=>{try{let data=await(await api('/inspector')).json();$('#inspectBody').innerHTML=Object.entries(data).map(([k,v])=>`<section><h3>${k} (${v.length})</h3>${v.map(recordCard).join('')||'<p class="empty">No records yet.</p>'}</section>`).join('');$('#ranking').innerHTML='';$('#inspector').showModal()}catch(e){showError(e)}};
$('#memorySearch').onsubmit=async e=>{e.preventDefault();let q=$('#memoryQuery').value.trim();if(!q)return;try{let hits=await(await api('/memories/search?q='+encodeURIComponent(q))).json();$('#ranking').innerHTML=`<h3>Retrieval ranking</h3>${hits.map((x,i)=>`<div class="rank"><b>#${i+1}</b><span>${escape(x.content)}</span><code>${Number(x.score).toFixed(4)}</code></div>`).join('')||'<p class="empty">No relevant active memories.</p>'}`}catch(e){showError(e)}};
document.querySelectorAll('.prompts button').forEach(b=>b.onclick=()=>{$('#input').value=b.textContent;$('#composer').requestSubmit()});$('#input').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#composer').requestSubmit()}};boot();
